-- =========================================================
-- VALORIA STORE <-> MTA database integration
-- Target database: play
-- Run AFTER importing play.sql
-- =========================================================

USE `play`;

-- VALORIA website admin credentials (password is stored as SHA-256, not plaintext)
CREATE TABLE IF NOT EXISTS `valoria_admins` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password_sha256` char(64) NOT NULL,
  `role` varchar(32) NOT NULL DEFAULT 'admin',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_valoria_admin_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `valoria_admins` (`email`,`password_sha256`,`role`,`enabled`)
VALUES ('Alone@admin.com','e25ee2d5fc6961de2f33835e0ab46cc52f4faea2cb17b2aeb5ad1463a1b171ce','admin',1)
ON DUPLICATE KEY UPDATE
  `password_sha256`=VALUES(`password_sha256`),
  `role`='admin',
  `enabled`=1;


CREATE TABLE IF NOT EXISTS `valoria_products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_id` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `category` varchar(50) NOT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0,
  `currency` varchar(10) NOT NULL DEFAULT 'USD',
  `delivery_type` varchar(32) NOT NULL DEFAULT 'manual',
  `delivery_value` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_valoria_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `valoria_orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` varchar(64) NOT NULL,
  `account_id` int NOT NULL,
  `character_id` int DEFAULT 0,
  `account_name` varchar(100) NOT NULL,
  `character_name` varchar(255) DEFAULT '',
  `website_email` varchar(255) NOT NULL,
  `payment_method` varchar(50) NOT NULL,
  `transaction_id` varchar(255) NOT NULL,
  `items_json` longtext NOT NULL,
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0,
  `currency` varchar(10) NOT NULL DEFAULT 'USD',
  `status` enum('PENDING','APPROVED','REJECTED','DELIVERED','DELIVERY_FAILED') NOT NULL DEFAULT 'PENDING',
  `admin_note` text,
  `approved_by` varchar(255) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `delivery_result` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_valoria_order_id` (`order_id`),
  KEY `idx_valoria_account` (`account_id`),
  KEY `idx_valoria_status` (`status`),
  KEY `idx_valoria_tx` (`transaction_id`),
  CONSTRAINT `fk_valoria_order_account`
    FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Optional audit log for every approval/rejection/delivery.
CREATE TABLE IF NOT EXISTS `valoria_order_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` varchar(64) NOT NULL,
  `action` varchar(50) NOT NULL,
  `actor` varchar(255) DEFAULT NULL,
  `details` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_valoria_log_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed/update the 72 products from the website catalog.
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-001','تصفير السالبات + تغيير اسم الحساب','خدمات',5,'USD','manual',NULL,'') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-002','بورش 911','مركبات',20,'USD','vehicle',NULL,'assets/products/item-002.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-003','بي إم دبليو جديدة','مركبات',30,'USD','vehicle',NULL,'assets/products/item-003.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-004','لامبورجيني 2024','مركبات',30,'USD','vehicle',NULL,'assets/products/item-004.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-005','روز جديد','مركبات',30,'USD','vehicle',NULL,'assets/products/item-005.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-006','برابوس G900','مركبات',25,'USD','vehicle',NULL,'assets/products/item-006.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-007','موتوسيكل G1','مركبات',7,'USD','vehicle',NULL,'assets/products/item-007.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-008','رنج روفر 2024','مركبات',25,'USD','vehicle',NULL,'assets/products/item-008.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-009','نيسان ددسن 2014','مركبات',18,'USD','vehicle',NULL,'assets/products/item-009.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-010','تويوتا لاند كروزر','مركبات',18,'USD','vehicle',NULL,'assets/products/item-010.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-011','سيارة مميزة جديدة','مركبات',20,'USD','vehicle',NULL,'assets/products/item-011.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-012','نيسان بيك أب','مركبات',15,'USD','vehicle',NULL,'assets/products/item-012.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-013','كونيجسيج','مركبات',10,'USD','vehicle',NULL,'assets/products/item-013.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-014','رنج روفر','مركبات',15,'USD','vehicle',NULL,'assets/products/item-014.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-015','بنتلي','مركبات',15,'USD','vehicle',NULL,'assets/products/item-015.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-016','مرسيدس G-Class 6x6','مركبات',30,'USD','vehicle',NULL,'assets/products/item-016.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-017','مرسيدس بيك أب','مركبات',10,'USD','vehicle',NULL,'assets/products/item-017.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-018','مرسيدس بونتو','مركبات',25,'USD','vehicle',NULL,'assets/products/item-018.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-019','دودج فايبر','مركبات',15,'USD','vehicle',NULL,'assets/products/item-019.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-020','بوغاتي أتلانتيك','مركبات',26,'USD','vehicle',NULL,'assets/products/item-020.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-021','طائرة خاصة','مركبات',15,'USD','vehicle',NULL,'assets/products/item-021.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-022','فورد موديل T (دراجة)','مركبات',10,'USD','vehicle',NULL,'assets/products/item-022.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-023','بي إم دبليو M4','مركبات',15,'USD','vehicle',NULL,'assets/products/item-023.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-024','فرازي أف كلاس','مركبات',12,'USD','vehicle',NULL,'assets/products/item-024.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-025','هونداي جينيسيس','مركبات',15,'USD','vehicle',NULL,'assets/products/item-025.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-026','رصيد موقع 10','رصيد',10,'USD','credit','10','assets/products/item-031.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-027','رصيد موقع 25','رصيد',25,'USD','credit','25','assets/products/item-032.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-028','رصيد موقع 50','رصيد',50,'USD','credit','50','assets/products/item-033.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-029','رصيد موقع 75','رصيد',75,'USD','credit','75','assets/products/item-034.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-030','رصيد موقع 100','رصيد',100,'USD','credit','100','assets/products/item-035.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-031','بطاقة توثيق العائلة','خدمات',15,'USD','manual',NULL,'assets/products/item-042.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-032','رادار الرينج','مركبات',25,'USD','vehicle',NULL,'assets/products/item-032.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-033','رأس مقطورة مرسيدس','مركبات',20,'USD','vehicle',NULL,'assets/products/item-033.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-034','برابوس','مركبات',25,'USD','vehicle',NULL,'assets/products/item-034.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-035','باقة مميزة','عضويات',10,'USD','manual',NULL,'assets/products/item-035.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-036','بريميوم كلاس','عضويات',15,'USD','manual',NULL,'assets/products/item-036.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-037','بطاقة البيدج','خدمات',20,'USD','manual',NULL,'assets/products/item-037.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-038','دودج شارجر 2023','مركبات',15,'USD','vehicle',NULL,'assets/products/item-038.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-039','رولز رويس كولينان 2023','مركبات',20,'USD','vehicle',NULL,'assets/products/item-039.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-040','بي إم دبليو 2025','مركبات',20,'USD','vehicle',NULL,'assets/products/item-040.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-041','تويوتا سوبرا 2023','مركبات',20,'USD','vehicle',NULL,'assets/products/item-041.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-042','راعي بيزي','عضويات',5,'USD','manual',NULL,'assets/products/item-042.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-043','BMW E30 Drift','مركبات',20,'USD','vehicle',NULL,'assets/products/item-043.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-044','شاحنة سطحة هوريون','مركبات',15,'USD','vehicle',NULL,'assets/products/item-044.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-045','راعي فضي','عضويات',10,'USD','manual',NULL,'assets/products/item-045.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-046','راعي ذهبي','عضويات',15,'USD','manual',NULL,'assets/products/item-046.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-047','راعي استراتيجي','عضويات',20,'USD','manual',NULL,'assets/products/item-047.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-048','راعي أساسي','عضويات',25,'USD','manual',NULL,'assets/products/item-048.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-049','Jeep Wrangler','مركبات',15,'USD','vehicle',NULL,'assets/products/item-049.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-050','Tesla Roadster 2026','مركبات',25,'USD','vehicle',NULL,'assets/products/item-050.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-051','أيدي تاني','خدمات',25,'USD','manual',NULL,'assets/products/item-051.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-052','كارت تعديل سيارة فل','خدمات',5,'USD','manual',NULL,'assets/products/item-052.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-053','فورد موديل T (دراجة)','مركبات',10,'USD','vehicle',NULL,'assets/products/item-053.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-054','سكن خاص','خدمات',5,'USD','manual',NULL,'assets/products/item-054.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-055','Ford Mustang (Police)','مركبات',12,'USD','vehicle',NULL,'assets/products/item-055.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-056','AMG ONE','مركبات',35,'USD','vehicle',NULL,'assets/products/item-056.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-057','تفعيل حساب دائم','خدمات',50,'USD','manual',NULL,'assets/products/item-057.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-058','تفعيل حساب أول ديسكورد','خدمات',10,'USD','manual',NULL,'assets/products/item-058.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-059','حظر دائم','خدمات',25,'USD','manual',NULL,'assets/products/item-059.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-060','حظر مؤقت','خدمات',5,'USD','manual',NULL,'assets/products/item-060.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-061','إلغاء تفعيل حساب دائم','خدمات',30,'USD','manual',NULL,'assets/products/item-061.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-062','إلغاء تفعيل حساب مؤقت','خدمات',15,'USD','manual',NULL,'assets/products/item-062.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-063','بلاغ ليست مايك','خدمات',5,'USD','manual',NULL,'assets/products/item-063.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-064','إلغاء منع توظيف مؤقت','خدمات',10,'USD','manual',NULL,'assets/products/item-064.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-065','إلغاء منع توظيف دائم','خدمات',30,'USD','manual',NULL,'assets/products/item-065.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-066','إلغاء الحظر الدائم','خدمات',15,'USD','manual',NULL,'assets/products/item-066.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-067','غرامة فك منع حظر السلاح','خدمات',5,'USD','manual',NULL,'assets/products/item-067.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-068','إيدي تاني','خدمات',15,'USD','manual',NULL,'assets/products/item-068.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-069','كتاب الحركات دائم','خدمات',15,'USD','manual',NULL,'assets/products/item-069.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-070','غرامة فك منع توظيف دائم','خدمات',30,'USD','manual',NULL,'assets/products/item-070.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-071','إيدي تاني','خدمات',15,'USD','manual',NULL,'assets/products/item-071.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;
INSERT INTO `valoria_products` (`product_id`,`name`,`category`,`price`,`currency`,`delivery_type`,`delivery_value`,`image`) VALUES ('ulg-072','كتاب الحركات دائم','خدمات',15,'USD','manual',NULL,'assets/products/item-072.jpg') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`category`=VALUES(`category`),`price`=VALUES(`price`),`currency`=VALUES(`currency`),`delivery_type`=VALUES(`delivery_type`),`delivery_value`=VALUES(`delivery_value`),`image`=VALUES(`image`),`enabled`=1;

-- Helpful index for matching a game account by its real game email.
CREATE INDEX `idx_accounts_email_username` ON `accounts` (`email`, `username`(100));

-- NOTE:
-- Vehicle/service delivery values are intentionally not guessed here.
-- For a vehicle, set valoria_products.delivery_value to the correct
-- vehicles_shop.id after confirming the exact custom vehicle.
-- For a service, the MTA resource receives a manual-delivery hook.
