const express=require('express');const cors=require('cors');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
const PORT=process.env.PORT||3000;const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'Alone@admin.com').toLowerCase();const ADMIN_PASSWORD_SHA256=process.env.ADMIN_PASSWORD_SHA256||'e25ee2d5fc6961de2f33835e0ab46cc52f4faea2cb17b2aeb5ad1463a1b171ce';
const STORE=path.join(__dirname,'orders.json');if(!fs.existsSync(STORE))fs.writeFileSync(STORE,'[]');let sessions=new Set();
function readOrders(){try{return JSON.parse(fs.readFileSync(STORE,'utf8'));}catch{return [];}}function writeOrders(x){fs.writeFileSync(STORE,JSON.stringify(x,null,2));}
function admin(req,res,next){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):'';if(!sessions.has(t))return res.status(401).json({message:'غير مصرح'});next();}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'VALORIA STORE',time:new Date().toISOString()}));
app.post('/api/login',(req,res)=>{const {email,password}=req.body||{};if(!email||!password)return res.status(400).json({message:'البيانات ناقصة'});const hash=crypto.createHash('sha256').update(password).digest('hex');if(email.toLowerCase()===ADMIN_EMAIL&&hash===ADMIN_PASSWORD_SHA256){const token=crypto.randomBytes(32).toString('hex');sessions.add(token);return res.json({message:'تم تسجيل دخول الأدمن',role:'admin',token});}res.status(401).json({message:'الإيميل أو كلمة المرور غير صحيحة'});});
app.post('/api/orders',(req,res)=>{const {email,mtaAccount,paymentMethod,transactionId,products,total}=req.body||{};if(!email||!mtaAccount||!paymentMethod||!transactionId||!Array.isArray(products)||!products.length)return res.status(400).json({message:'بيانات الطلب ناقصة'});const orders=readOrders();const order={id:'VAL-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),email,mtaAccount,paymentMethod,transactionId,products,total:Number(total||0),status:'PENDING'};orders.unshift(order);writeOrders(orders);console.log('[VALORIA ORDER]',order.id,email,mtaAccount);res.json({ok:true,order});});
app.get('/api/admin/orders',admin,(req,res)=>res.json(readOrders()));
app.post('/api/admin/orders/:id/status',admin,(req,res)=>{const {status}=req.body||{};if(!['PAID','REJECTED'].includes(status))return res.status(400).json({message:'حالة غير صحيحة'});const orders=readOrders();const o=orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({message:'الطلب غير موجود'});o.status=status;o.updatedAt=new Date().toISOString();writeOrders(orders);res.json({ok:true,order:o});});
app.listen(PORT,()=>console.log('VALORIA backend running on '+PORT));
